/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull

class LexerTest {
    @Test fun canCreateLexer() {
        assertNotNull(true, "app should have a greeting")
    }
}
