@startuml

package lexer {

  interface Lexer {
    + getTokens(ContentManager) : Stream<Token>
  }

  class Splitter { 
  }

  interface ContentManager {
    + getLines() : Stream<String>;
  }
}

package parser {
  class Parser {
    + getAST(Stream<Token>) : Node<Token> 
  }
}

package config {
  file Token {
    class Token {}
    class TokenRule {}
    class TokenIdentifier {}
    enum TokenType {}

  }

  class Definition {}
}

package utils {
  class Node {}
  class Position {}
  
  file Result {
    interface Result {}
    class Success {}
    class Failure {}
  }
}

class app {
  + main()
}


@enduml
